name       : haskell-cmdargs
version    : 0.10.20
release    : 2
source     :
    - http://hackage.haskell.org/package/cmdargs-0.10.20/cmdargs-0.10.20.tar.gz : 0e269dc48c3d4c0447c96ffd772a6fe69dfa1260c323f4cd7bf171cbf2ab7331
license    : BSD-3-Clause
component  : programming.haskell
summary    : Command line argument processing
description: |
    Command line argument processing
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
